local STRINGS = GLOBAL.STRINGS
local Language = GLOBAL.SCHEME_LANGUAGE

STRINGS.TAGGABLE_REMOVE_BUTTON = "Remove"
STRINGS.TAGGABLE_REFRESH_BUTTON = "Refresh"
STRINGS.TAGGABLE_SELECT_DESTINATION = "Select Destination"

STRINGS.ACTION_SPAWNG = "Spawn Scheme Tunnel"
STRINGS.ACTION_CONFIGG = "Configurate"
STRINGS.ACTION_SELECTG = "Select"

STRINGS.NAMES.SCHEMETOOL = "Scheme tool"
STRINGS.RECIPE_DESC.SCHEMETOOL = "Scheme manipulation tool."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SCHEMETOOL = "I feel someone's watching me."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SCHEMETOOL = "I can feel.. Abysm."
STRINGS.CHARACTERS.WX78.DESCRIBE.SCHEMETOOL = "FINALLY, I CAN GET THE WORLD"

STRINGS.NAMES.TUNNEL = "Destination"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TUNNEL = "How creepy!\nIt seems doesn't have a destination."
STRINGS.CHARACTERS.WX78.DESCRIBE.TUNNEL = "DESTINATION NOT DETECTED"

STRINGS.CHARACTERS.GENERIC.LOWUSEGSANITY = "This is not a sane thing to do!"
STRINGS.CHARACTERS.WAXWELL.LOWUSEGSANITY = "I'm not dapper enough to dive in somewhere unknown."
STRINGS.CHARACTERS.WOLFGANG.LOWUSEGSANITY = "Wolfgang is scared!"
STRINGS.CHARACTERS.WOODIE.LOWUSEGSANITY = "It's too scary out to go."
STRINGS.CHARACTERS.WX78.LOWUSEGSANITY = "FETAL ERROR : UNWILLING PROCESS"

STRINGS.CHARACTERS.GENERIC.LOWCGSANITY = "I don't have enough sanity."
STRINGS.CHARACTERS.WAXWELL.LOWCGSANITY = "My mind will not resist if I do."
STRINGS.CHARACTERS.WOLFGANG.LOWCGSANITY = "Wolfgang is scared to do!"
STRINGS.CHARACTERS.WX78.LOWCGSANITY = "FETAL ERROR : UNWILLING PROCESS"

STRINGS.CHARACTERS.WX78.NODANGERSCHEME = "WARNING: THREAT DETECTED."
STRINGS.CHARACTERS.GENERIC.NODANGERSCHEME = "It's too dangerous right now!"
STRINGS.CHARACTERS.WEBBER.NODANGERSCHEME = "Can't! There's scary-biteys about!"
STRINGS.CHARACTERS.WILLOW.NODANGERSCHEME = "I'm not leaving now!"
STRINGS.CHARACTERS.WOODIE.NODANGERSCHEME = "I better deal with these hosers first."
STRINGS.CHARACTERS.WINONA.NODANGERSCHEME = "It ain't safe."
STRINGS.CHARACTERS.WOLFGANG.NODANGERSCHEME = "Wolfgang fight rather flee!"
STRINGS.CHARACTERS.WICKERBOTTOM.NODANGERSCHEME = "Were I to lose focus now I'd be sure to sustain bodily injury."
STRINGS.CHARACTERS.WENDY.NODANGERSCHEME = "No time do that, death has finally come for me!"
STRINGS.CHARACTERS.WAXWELL.NODANGERSCHEME = "That's a terrible idea right now."
STRINGS.CHARACTERS.WATHGRITHR.NODANGERSCHEME = "Only a coward would leave now!"

if Language == "kr" then

STRINGS.ACTION_SPAWNG = "스키마 게이트 소환"
STRINGS.ACTION_CONFIGG = "변경"
STRINGS.ACTION_SELECTG = "선택"

STRINGS.TAGGABLE_REMOVE_BUTTON = "제거"
STRINGS.TAGGABLE_REFRESH_BUTTON = "새로고침"
STRINGS.TAGGABLE_SELECT_DESTINATION = "목적지를 선택하세요"

STRINGS.NAMES.SCHEMETOOL = "스키마도구"
STRINGS.RECIPE_DESC.SCHEMETOOL = "스키마 관리 도구"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SCHEMETOOL = "누군가 지켜보는 것 같아."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SCHEMETOOL = "나락이 느껴지는군."
STRINGS.CHARACTERS.WX78.DESCRIBE.SCHEMETOOL = "마침내 세계를 지배할 수 있게됨"

STRINGS.NAMES.TUNNEL = "목적지"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TUNNEL = "정말 끔찍하군!\n목적지도 없는거 같아."
STRINGS.CHARACTERS.WX78.DESCRIBE.TUNNEL = "목적지를 찾을 수 없음"

STRINGS.CHARACTERS.GENERIC.LOWUSEGSANITY = "이건 미친짓이야!"
STRINGS.CHARACTERS.WAXWELL.LOWUSEGSANITY = "난 알 수 없는 곳으로 뛰어들 만큼 대담하지 않아."
STRINGS.CHARACTERS.WOLFGANG.LOWUSEGSANITY = "볼프강 무섭다!"
STRINGS.CHARACTERS.WOODIE.LOWUSEGSANITY = "그러기엔 너무 무섭군."
STRINGS.CHARACTERS.WX78.LOWUSEGSANITY = "치명적인 오류 : 작업이 내키치 않음"

STRINGS.CHARACTERS.GENERIC.LOWCGSANITY = "정신력이 부족해"
STRINGS.CHARACTERS.WAXWELL.LOWCGSANITY = "만약 그런다면 내 정신이 버티질 못하겠군."
STRINGS.CHARACTERS.WOLFGANG.LOWCGSANITY = "볼프강 무섭다!"
STRINGS.CHARACTERS.WX78.LOWCGSANITY = "치명적인 오류 : 작업이 내키치 않음"

STRINGS.CHARACTERS.WX78.NODANGERSCHEME = "경고 : 위험 감지됨"
STRINGS.CHARACTERS.GENERIC.NODANGERSCHEME = "그러기엔 너무 위험해!"
STRINGS.CHARACTERS.WEBBER.NODANGERSCHEME = "안돼! 저기에는 무서운 깨물이들이 있어!"
STRINGS.CHARACTERS.WILLOW.NODANGERSCHEME = "나 지금 떠날 때가 아니야!"
STRINGS.CHARACTERS.WOODIE.NODANGERSCHEME = "이 잔챙이들을 먼저 처리했으면 좋겠군."
STRINGS.CHARACTERS.WINONA.NODANGERSCHEME = "그닥 안전하지 않아."
STRINGS.CHARACTERS.WOLFGANG.NODANGERSCHEME = "볼프강 도망가지 않는다! 싸운다!"
STRINGS.CHARACTERS.WICKERBOTTOM.NODANGERSCHEME = "만약 내가 주의를 잃는다면 난 신체적 상해를 입고 말 게야."
STRINGS.CHARACTERS.WENDY.NODANGERSCHEME = "그럴 시간은 없어요, 마침내 죽음이 제게 오고 있다구요!"
STRINGS.CHARACTERS.WAXWELL.NODANGERSCHEME = "지금 그러는건 말도 안되는군."
STRINGS.CHARACTERS.WATHGRITHR.NODANGERSCHEME = "도망은 비겁한 자들의 변명이다!"

end