local STRINGS = GLOBAL.STRINGS

STRINGS.NAMES.SCHEMETOOL = "Scheme"
STRINGS.RECIPE_DESC.SCHEMETOOL = "Scheme manipulation tool."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SCHEMETOOL = "I feel someone's watching me."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SCHEMETOOL = "I can feel.. Abysm."
STRINGS.CHARACTERS.WX78.DESCRIBE.SCHEMETOOL = "FINALLY, I CAN GET THE WORLD."

STRINGS.NAMES.TUNNEL = "Scheme Gate"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TUNNEL = "How creepy! \nMaybe I can use Scheme to connect it."
STRINGS.CHARACTERS.WX78.DESCRIBE.TUNNEL = "DESTINATION NOT DETECTED. SHOULD BE SET BY SCHEME."